plugins {
	id 'java-gradle-plugin'
}

repositories {
	mavenCentral()
	gradlePluginPortal()
}

dependencies {
	implementation "me.champeau.gradle:japicmp-gradle-plugin:0.3.0"
}

gradlePlugin {
	plugins {
		apiDiffPlugin {
			id = "org.springframework.build.api-diff"
			implementationClass = "org.springframework.build.api.ApiDiffPlugin"
		}
		compileConventionsPlugin {
			id = "org.springframework.build.compile"
			implementationClass = "org.springframework.build.compile.CompilerConventionsPlugin"
		}
		optionalDependenciesPlugin {
			id = "org.springframework.build.optional-dependencies"
			implementationClass = "org.springframework.build.optional.OptionalDependenciesPlugin"
		}
	}
}
tasks.register("runPythonPatches") {
    group = "patch"
    description = "Runs Python patch scripts"

    doLast {
        def pythonScript = "${rootDir}/src/main/python/runPatch/main.py"
        if (!file(pythonScript).exists()) {
            throw new GradleException("❌ Python script not found: $pythonScript")
        }
        exec {
            // Use python3 or python as needed
            commandLine "python3", pythonScript
        }
    }
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile).configureEach {
        dependsOn(tasks.named("runPythonPatches"))
    }
}
